[tool.black]
line-length = 120
target_version = ['py38',]

[tool.isort]
profile = "black"

[tool.bandit]
exclude_dirs = ["tests",]
include_dirs = ["streams",]
skips = ["B105", "B311"]

[tool.pylint.format]
max-line-length=120

[tool.pylint.messages_control]
disable=["C","R","W",]

[tool.pylint.design]
max-parents=13

[tool.pylint.typecheck]
generated-members=["db_engine", "objects", "_fields", "connect", "Error"]
ignored-modules=[
    "streams","tests", "configs",
    "process_core", "process_note"
]

[tool.pytest.ini_options]
filterwarnings=["ignore::DeprecationWarning",]
testpaths=["tests",]
