# Generated by Django 2.2.16 on 2020-10-22 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_comments_listings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='user_id',
            new_name='user',
        ),
    ]
